default_stages: [pre-commit, pre-push]

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main, --branch, dev]
      - id: check-added-large-files
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.2"
    hooks:
      - id: ruff
        stages: [pre-push]
      - id: ruff-format

  - repo: https://github.com/pycqa/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        stages: [pre-push]
        exclude: ^tests/
        args: [-c, pyproject.toml, -r, ./src]
  
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest -v ./tests
        language: system
        types: [python]
        pass_filenames: false
