"""
autogen

Revision ID: f3ea16a50cdf
Revises:
Create Date: 2025-03-28 12:19:38.156719

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3ea16a50cdf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cpu",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("brand", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("cores", sa.Integer(), nullable=False),
        sa.Column("threads", sa.Integer(), nullable=False),
        sa.Column("base_clock", sa.Float(), nullable=False),
        sa.Column("boost_clock", sa.Float(), nullable=True),
        sa.Column("tdp", sa.Integer(), nullable=False),
        sa.Column("socket", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("architecture", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("characteristics", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("integrated_graphics", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cpu")
    # ### end Alembic commands ###
